Developer:       SRUNION
Project Manager: Manager Name 
#  General Information
#  -------------------
#  Repository Name       : faam
#  Issue Name         : faam.#1
#  Process Associated : git
#  Project Number : 1
#  Project Description: Audit Activity Reports Enhancment
#  Object Source File Location and Name : c:\github\faam.wiki\faam.#1.txt.asciidoc

faam.#1 Issue Instructions

Objects added/modified in this issue:
rdf/ufa_audit_rnaovxx_m.rdf
rdf/ufa_audit_roanyud_m.rdf
rdf/ufa_audit_roausdf_m.rdf
rdf/ufa_audit_rpaapmt_m.rdf
rdf/ufa_audit_rpaawrd_m.rdf
rdf/ufa_audit_sap_m.rdf
exp/ufa_audit_rnaovxx_m.exp
exp/ufa_audit_roanyud_m.exp
exp/ufa_audit_roausdf_m.exp
exp/ufa_audit_rpaapmt_m.exp
exp/ufa_audit_rpaawrd_m.exp
exp/ufa_audit_sap_m.exp
exp/ufa_audit_activity_c.exp

Name                                Type                  Application 
---------------------------------------------------------------------
rdf/ufa_audit_rnaovxx_m.rdf         RDF
rdf/ufa_audit_roanyud_m.rdf         RDF
rdf/ufa_audit_roausdf_m.rdf         RDF
rdf/ufa_audit_rpaapmt_m.rdf         RDF
rdf/ufa_audit_rpaawrd_m.rdf         RDF
exp\ufa_audit_rnaovxx_m.exp         JOB                   
exp\ufa_audit_roanyud_m.exp         JOB                        
exp\ufa_audit_roausdf_m.exp         JOB                       
exp\ufa_audit_rpaapmt_m.exp         JOB                       
exp\ufa_audit_rpaawrd_m.exp         JOB                       
exp\ufa_audit_sap_m.exp             JOB                       
exp\ufa_audit_activity_c.exp        PROCESS FLOW              

Instructions
-------------------------------------------
Special Instructions for SFADVLP
Move .rdf to unix directory in Trusty: /home/appworx-wd/dvlp/<<application>>/rdf
 
Special Instructions for SFAUAT/SFAUATU
Move .rdf to unix directory in truly: /home/appworx-wd/dvlp/<<application>>/rdf
Move .rdf to unix directory in wh500: /home/appworx-wd/dvlp/<<application>>/rdf

Special Instructions for SFAPROD
Move .rdf to unix directory in thor: /home/appworx-wd/dvlp/<<application>>/rdf